### ISSUE TITLE
Empty test suite.

### ISSUE THREAD

**Issue by ManuelEMR** [vanniktech/RxRiddles#11] opened 2018-05-31 16:22 UTC
Im getting the following error in Android Studio:

Class not found: "com.vanniktech.rxriddles.Riddle1Test"Empty test suite.

Already tried, deleting the configuration, invalidating cache, but it still doesnt find the class.

**Comment by vanniktech** [comment] 2018-05-31 16:53
That's where. Are you using Android Studio 3.1.2?

You can also try deleting the .idea directory.
Otherwise you can execute the tests using `./gradlew test`

**Comment by vanniktech** [comment] 2018-06-01 13:21
I'll close this as I can't reproduce this. Try updating your AS.

**Closed by vanniktech** 2018-06-01 13:21 UTC

**Comment by vanniktech** [comment] 2018-06-13 08:29
There is no 3.2.3 AFAIK. 3.2.18 is alpha and hence you might need to update the Plugin version.

**Comment by FrancoisBlavoet** [comment] 2018-06-13 17:04
Sorry mistyped; I meant 3.1.3

**Comment by vanniktech** [comment] 2018-06-14 07:33
I've also gotten this now on a different project. I'm pretty sure it's an AS bug. The best way to run the tests is the command line. That one always works.

**Comment by jshvarts** [comment] 2018-06-14 10:58
Yes I’ve seen it in several different projects used with the latest stable AS. Oddly usually once you run your test on the command line, it can be run within AS.

**Comment by vanniktech** [comment] 2018-06-14 14:05
Yes I've noticed the same behavior. And yes you can filter them too. :+1:
